/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActRouteImport } from './routes/act'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as InitiativesRouteImport } from './routes/initiatives'
import { Route as PactRouteImport } from './routes/pact'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as InitiativesIndexRouteImport } from './routes/initiatives.index'
import { Route as InitiativesSlugRouteImport } from './routes/initiatives.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActRoute = ActRouteImport.update({
  id: '/act',
  path: '/act',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesRoute = InitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const PactRoute = PactRouteImport.update({
  id: '/pact',
  path: '/pact',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesIndexRoute = InitiativesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InitiativesRoute,
} as any)
const InitiativesSlugRoute = InitiativesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InitiativesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/act': typeof ActRoute
  '/atlas': typeof AtlasRoute
  '/initiatives': typeof InitiativesRouteWithChildren
  '/pact': typeof PactRoute
  '/timeline': typeof TimelineRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/initiatives/': typeof InitiativesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/act': typeof ActRoute
  '/atlas': typeof AtlasRoute
  '/pact': typeof PactRoute
  '/timeline': typeof TimelineRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/initiatives': typeof InitiativesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/act': typeof ActRoute
  '/atlas': typeof AtlasRoute
  '/initiatives': typeof InitiativesRouteWithChildren
  '/pact': typeof PactRoute
  '/timeline': typeof TimelineRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/initiatives/': typeof InitiativesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/act'
    | '/atlas'
    | '/initiatives'
    | '/pact'
    | '/timeline'
    | '/initiatives/$slug'
    | '/initiatives/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/act'
    | '/atlas'
    | '/pact'
    | '/timeline'
    | '/initiatives/$slug'
    | '/initiatives'
  id:
    | '__root__'
    | '/'
    | '/act'
    | '/atlas'
    | '/initiatives'
    | '/pact'
    | '/timeline'
    | '/initiatives/$slug'
    | '/initiatives/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActRoute: typeof ActRoute
  AtlasRoute: typeof AtlasRoute
  InitiativesRoute: typeof InitiativesRouteWithChildren
  PactRoute: typeof PactRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/act': {
      id: '/act'
      path: '/act'
      fullPath: '/act'
      preLoaderRoute: typeof ActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives': {
      id: '/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof InitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pact': {
      id: '/pact'
      path: '/pact'
      fullPath: '/pact'
      preLoaderRoute: typeof PactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/': {
      id: '/initiatives/'
      path: '/'
      fullPath: '/initiatives/'
      preLoaderRoute: typeof InitiativesIndexRouteImport
      parentRoute: typeof InitiativesRoute
    }
    '/initiatives/$slug': {
      id: '/initiatives/$slug'
      path: '/$slug'
      fullPath: '/initiatives/$slug'
      preLoaderRoute: typeof InitiativesSlugRouteImport
      parentRoute: typeof InitiativesRoute
    }
  }
}

interface InitiativesRouteChildren {
  InitiativesSlugRoute: typeof InitiativesSlugRoute
  InitiativesIndexRoute: typeof InitiativesIndexRoute
}

const InitiativesRouteChildren: InitiativesRouteChildren = {
  InitiativesSlugRoute: InitiativesSlugRoute,
  InitiativesIndexRoute: InitiativesIndexRoute,
}

const InitiativesRouteWithChildren = InitiativesRoute._addFileChildren(
  InitiativesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActRoute: ActRoute,
  AtlasRoute: AtlasRoute,
  InitiativesRoute: InitiativesRouteWithChildren,
  PactRoute: PactRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
